stages:
  - test

.in-docker:
  tags:
    - docker
  image: alpine

.php-job:
  extends: .in-docker
  image: spaceonfire/nginx-php-fpm:latest-7.2

.composer-job:
  extends: .php-job
  before_script:
    - composer install
  cache:
    paths:
      - vendor
      - $COMPOSER_CACHE_DIR
  variables:
    COMPOSER_CACHE_DIR: $CI_PROJECT_DIR/._composer-cache

##
## "Test" stage jobs
##

codestyle:
  extends: .composer-job
  stage: test
  script:
    - composer codestyle -- --no-progress-bar --no-interaction

phpstan:
  extends: .composer-job
  stage: test
  script:
    - composer dump-autoload --classmap-authoritative
    - composer lint -- --no-interaction --no-progress

phpunit:
  extends: .composer-job
  stage: test
  script:
    - composer test
